name: script_inliner
description: A transformer to inline script content during a build.
version: 1.0.0
author: Seth Ladd <sethladd@gmail.com>
homepage: https://github.com/sethladd/script_inliner
dependencies:
  barback: '>=0.15.0 <0.16.0'
  html5lib: ">=0.12.0 <0.13.0"
  code_transformers: ">=0.2.3 <0.3.0"
dev_dependencies:
  browser: any
transformers:
- script_inliner
